### ISSUE TITLE
Question about SS cluster computation

### ISSUE THREAD

**Issue by giuseppecartella** [chenxy99/GazeXplain#1]
Congratulations on you interesting work!

 I have a question regarding the creation of the SS clusters and the SS metric computation.

From the source code, it seems that clusters are calculated by rescaling all the fixations coordinates to 512x384, and at the same time predicted coordinates are not scaled back to the original image size.

My question is the following: is there any specific reason for not creating the clusters and computing SS in the original image size?
I guess that the number of clusters can be different if the original image size is not 512x384.  Correct me if I am wrong. 

Thank you!
Giuseppe

**Comment by chenxy99** [comment]
Hello Giuseppe,

Thank you for your interest in our work.

Since we simultaneously train and infer on four fixation datasets, and to handle different scales easily, we follow the image scale used in Gazeformer, as our model is built upon it.

It is reasonable to scale back to the original image size and then evaluate the model's performance.

Thanks for your suggestion. I have updated the code from

```python
target_height = 384
target_width = 512
``` 
to

```python
target_height = 600
target_width = 800
``` 
in the script located at https://github.com/chenxy99/GazeXplain/blob/main/src/preprocess/OSIE/proprecess_OSIE_SScluster.py and verified whether the clusters remain the same with the following code:

``` python
clusters_600x800 = np.load(os.path.join(processed_root, 'clusters_600x800.npy'), allow_pickle=True).item()
clusters = np.load(os.path.join(processed_root, 'clusters.npy'), allow_pickle=True).item()

different_count = 0
count = 0
for key in clusters:
    clusters_600x800_sample = clusters_600x800[key]
    clusters_sample = clusters[key]

    different_count += (clusters_600x800_sample["cluster"].labels_ != clusters_sample["cluster"].labels_).sum()
    count += len(clusters_600x800_sample["cluster"].labels_)
``` 
The results are:

``` python
different_count = 0
count = 93821
``` 
This indicates that the fixation points are assigned to the same labels regardless of the scale used (600x800 vs. 512x384). However, I agree that it would be better to predict coordinates and then scale them back to the original image size.

Best regards,
Xianyu

**Comment by giuseppecartella** [comment]
Thank you very much for your prompt feedback and the clarification about the clusters!

Giuseppe
